import os

filepath = "alembic/versions/05ef48b3d100_add_location_tracking_to_profile.py"
with open(filepath, "r") as f:
    lines = f.readlines()

new_lines = []
in_upgrade = False
in_downgrade = False

for line in lines:
    if line.startswith("def upgrade() -> None:"):
        in_upgrade = True
        new_lines.append(line)
        continue
    if line.startswith("def downgrade() -> None:"):
        in_upgrade = False
        in_downgrade = True
        new_lines.append(line)
        continue

    if in_upgrade:
        if "op.add_column('profiles'" in line:
            new_lines.append(line)
        elif line.strip() == '"""Upgrade schema."""' or line.strip() == '# ### commands auto generated by Alembic - please adjust! ###' or line.strip() == '# ### end Alembic commands ###' or line.strip() == '':
            new_lines.append(line)
    elif in_downgrade:
        if "op.drop_column('profiles'" in line and "preferred_unit_ids" not in line:
            new_lines.append(line)
        elif line.strip() == '"""Downgrade schema."""' or line.strip() == '# ### commands auto generated by Alembic - please adjust! ###' or line.strip() == '# ### end Alembic commands ###' or line.strip() == '':
            new_lines.append(line)
    else:
        new_lines.append(line)

with open(filepath, "w") as f:
    f.writelines(new_lines)
