"""add location tracking to profile

Revision ID: 05ef48b3d100
Revises: 5d06fa09e954
Create Date: 2026-07-02 14:21:59.089545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05ef48b3d100'
down_revision: Union[str, Sequence[str], None] = '5d06fa09e954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('home_address_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('home_location_lat', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('home_location_lng', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('live_location_sharing_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'live_location_sharing_enabled')
    op.drop_column('profiles', 'home_location_lng')
    op.drop_column('profiles', 'home_location_lat')
    op.drop_column('profiles', 'home_address_name')
    # ### end Alembic commands ###
