"""Add Facility and StaffMember models

Revision ID: 07744e4468ad
Revises: 542631274e9a
Create Date: 2026-06-30 16:05:16.525236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07744e4468ad'
down_revision: Union[str, Sequence[str], None] = '542631274e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PUBLIC', 'PRIVATE', 'MISSION', 'NGO', name='facility_type_enum'), nullable=False),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('services_offered', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('readiness', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('CLINICIAN', 'FACILITY_ADMIN', name='staff_role_enum'), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('assigned_patient_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITE_PENDING', 'DEACTIVATED', name='staff_status_enum'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_members')
    op.drop_table('facilities')
    # ### end Alembic commands ###
