"""add foreign keys to cycle tables

Revision ID: 10a42f21bd39
Revises: 7e4321f3514d
Create Date: 2026-07-01 15:02:09.061736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a42f21bd39'
down_revision: Union[str, Sequence[str], None] = '7e4321f3514d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cycle_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'form_submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'form_templates', 'facilities', ['facility_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'hmb_statuses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hmb_statuses', type_='foreignkey')
    op.drop_constraint(None, 'form_templates', type_='foreignkey')
    op.drop_constraint(None, 'form_submissions', type_='foreignkey')
    op.drop_constraint(None, 'cycle_entries', type_='foreignkey')
    # ### end Alembic commands ###
