"""Update Report model with optional dates and created_by

Revision ID: 14f1dfed3abf
Revises: f03b98702968
Create Date: 2026-07-08 15:33:45.945259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f1dfed3abf'
down_revision: Union[str, Sequence[str], None] = 'f03b98702968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('created_by', sa.UUID(), nullable=True))
    op.alter_column('reports', 'date_range_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('reports', 'date_range_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'reports', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'date_range_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('reports', 'date_range_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('reports', 'created_by')
    # ### end Alembic commands ###
