"""add_medical_history

Revision ID: 1fd586196156
Revises: e58c7146b849
Create Date: 2026-07-10 09:57:00.011632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fd586196156'
down_revision: Union[str, Sequence[str], None] = 'e58c7146b849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_history_custom_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('BOOLEAN', 'TEXT', 'NUMBER', 'SINGLE_SELECT', 'MULTI_SELECT', name='field_type_enum'), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_custom_fields_facility_id'), 'medical_history_custom_fields', ['facility_id'], unique=False)
    op.create_table('medical_history_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('last_updated_by', sa.UUID(), nullable=False),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('rh_factor', sa.String(), nullable=True),
    sa.Column('allergies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('chronic_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('surgical_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_pregnancies', sa.Integer(), nullable=False),
    sa.Column('previous_outcomes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('family_history', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_records_patient_user_id'), 'medical_history_records', ['patient_user_id'], unique=True)
    op.drop_index(op.f('ix_education_events_facility_id'), table_name='education_events')
    op.drop_table('education_events')
    op.drop_index(op.f('ix_education_content_facility_id'), table_name='education_content')
    op.drop_table('education_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_content',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('HYDRATION', 'NUTRITION', 'EXERCISE', 'MENTAL_HEALTH', 'GENERAL', name='content_category_enum'), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('target_stages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('education_content_facility_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('education_content_pkey'))
    )
    op.create_index(op.f('ix_education_content_facility_id'), 'education_content', ['facility_id'], unique=False)
    op.create_table('education_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('education_events_facility_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('education_events_pkey'))
    )
    op.create_index(op.f('ix_education_events_facility_id'), 'education_events', ['facility_id'], unique=False)
    op.drop_index(op.f('ix_medical_history_records_patient_user_id'), table_name='medical_history_records')
    op.drop_table('medical_history_records')
    op.drop_index(op.f('ix_medical_history_custom_fields_facility_id'), table_name='medical_history_custom_fields')
    op.drop_table('medical_history_custom_fields')
    # ### end Alembic commands ###
