"""add referral models

Revision ID: 37f287bc5357
Revises: 54035cfccaf1
Create Date: 2026-07-02 11:14:01.936126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37f287bc5357'
down_revision: Union[str, Sequence[str], None] = '54035cfccaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sending_facility_id', sa.UUID(), nullable=False),
    sa.Column('receiving_facility_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('EMERGENCY_COMPLICATION', 'SPECIALIST_CARE', 'LACK_OF_EQUIPMENT', 'PATIENT_PREFERENCE', 'OTHER', name='referral_reason_enum'), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'EMERGENCY', name='referral_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'IN_TRANSIT', 'ARRIVED', 'COMPLETED', 'CANCELLED', name='referral_status_enum'), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiving_facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sending_facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_referrals_receiving_facility_id'), 'referrals', ['receiving_facility_id'], unique=False)
    op.create_index(op.f('ix_referrals_sending_facility_id'), 'referrals', ['sending_facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_referrals_sending_facility_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_receiving_facility_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
