"""add typical_cycle_length_days to profile

Revision ID: 54035cfccaf1
Revises: 63ddef4483a2
Create Date: 2026-07-02 09:42:22.169407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54035cfccaf1'
down_revision: Union[str, Sequence[str], None] = '63ddef4483a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('typical_cycle_length_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'typical_cycle_length_days')
    # ### end Alembic commands ###
