"""Initial models

Revision ID: 542631274e9a
Revises: 
Create Date: 2026-06-30 14:52:03.101235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542631274e9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('MOTHER', 'CLINICIAN', 'FACILITY_ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', name='gender_enum'), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Enum('ASK_EVERYTIME', 'AUTO_SHARE', 'FACILITY_AUTO_SHARE', name='consent_type_enum'), nullable=False),
    sa.Column('grantee_id', sa.String(), nullable=True),
    sa.Column('grantee_name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_grantee_id'), 'consents', ['grantee_id'], unique=False)
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.Enum('PREGNANT', 'POSTPARTUM', 'NOT_PREGNANT', name='current_stage_enum'), nullable=True),
    sa.Column('preferred_unit_ids', sa.JSON(), nullable=False),
    sa.Column('emergency_sharing_preference', sa.Enum('ASK_FIRST', 'ALWAYS_SHARE', 'NEVER_SHARE', name='sharing_pref_enum'), nullable=True),
    sa.Column('notification_preference', sa.Enum('SMS', 'NOTIFICATION', name='notification_pref_enum'), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('companion_preference', sa.Enum('AI_DOC', 'PERSONAL_DOCTOR', 'BOTH', 'NONE', name='companion_pref_enum'), nullable=True),
    sa.Column('personal_doctor_id', sa.UUID(), nullable=True),
    sa.Column('personal_doctor_request_status', sa.Enum('ASSIGNED', 'PENDING', 'REJECTED', name='doctor_req_status_enum'), nullable=True),
    sa.Column('qr_passport_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_qr_passport_token'), 'profiles', ['qr_passport_token'], unique=True)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_qr_passport_token'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_grantee_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
