"""add emergency request model

Revision ID: 5d06fa09e954
Revises: 37f287bc5357
Create Date: 2026-07-02 12:52:02.993985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d06fa09e954'
down_revision: Union[str, Sequence[str], None] = '37f287bc5357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'RESOLVED', 'FALSE_ALARM', name='emergency_status_enum'), nullable=False),
    sa.Column('location_lat', sa.String(), nullable=True),
    sa.Column('location_lng', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_requests_facility_id'), 'emergency_requests', ['facility_id'], unique=False)
    op.create_index(op.f('ix_emergency_requests_patient_id'), 'emergency_requests', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_requests_patient_id'), table_name='emergency_requests')
    op.drop_index(op.f('ix_emergency_requests_facility_id'), table_name='emergency_requests')
    op.drop_table('emergency_requests')
    # ### end Alembic commands ###
