"""change preferred_unit_ids to single preferred_facility_id

Revision ID: 63ddef4483a2
Revises: 10a42f21bd39
Create Date: 2026-07-01 15:31:43.424640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ddef4483a2'
down_revision: Union[str, Sequence[str], None] = '10a42f21bd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('preferred_facility_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'facilities', ['preferred_facility_id'], ['id'], ondelete='SET NULL')
    op.drop_column('profiles', 'preferred_unit_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
