"""Add account_type and make password optional

Revision ID: 91eba63e58ed
Revises: 07744e4468ad
Create Date: 2026-06-30 16:38:43.402815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91eba63e58ed'
down_revision: Union[str, Sequence[str], None] = '07744e4468ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FULL', 'SMS_ONLY', name='account_type_enum').create(op.get_bind())
    op.add_column('users', sa.Column('account_type', sa.Enum('FULL', 'SMS_ONLY', name='account_type_enum'), server_default='FULL', nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'account_type')
    sa.Enum('FULL', 'SMS_ONLY', name='account_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
