"""feat: add cycle tracker models

Revision ID: c06720a2315e
Revises: 07744e4468ad
Create Date: 2026-06-30 20:55:07.359021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c06720a2315e'
down_revision: Union[str, Sequence[str], None] = '07744e4468ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('context', sa.Enum('CYCLE_ENTRY', 'CYCLE_SYMPTOM', name='form_context_enum'), nullable=False),
    sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_templates_slug'), 'form_templates', ['slug'], unique=False)
    op.create_table('hmb_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_action', sa.Enum('DISMISSED', 'TALK_TO_DOCTOR', name='hmb_ack_action_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hmb_statuses_user_id'), 'hmb_statuses', ['user_id'], unique=True)
    op.create_table('form_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context', sa.Enum('CYCLE_ENTRY', 'CYCLE_SYMPTOM', name='form_context_enum'), nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('client_generated_id', sa.String(), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_generated_id')
    )
    op.create_index(op.f('ix_form_submissions_template_id'), 'form_submissions', ['template_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_user_id'), 'form_submissions', ['user_id'], unique=False)
    op.create_table('cycle_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('pbac_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_cycle_entries_user_id'), 'cycle_entries', ['user_id'], unique=False)
    op.create_table('pbac_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_entry_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_type', sa.Enum('PAD', 'TAMPON', 'CLOT', name='pbac_item_type_enum'), nullable=False),
    sa.Column('soak_level', sa.Enum('LIGHTLY_SOAKED', 'MODERATELY_SOAKED', 'FULLY_SOAKED', name='pbac_soak_level_enum'), nullable=True),
    sa.Column('point_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_entry_id'], ['cycle_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pbac_items_cycle_entry_id'), 'pbac_items', ['cycle_entry_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', postgresql.ENUM('FULL', 'SMS_ONLY', name='account_type_enum'), server_default=sa.text("'FULL'::account_type_enum"), autoincrement=False, nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_pbac_items_cycle_entry_id'), table_name='pbac_items')
    op.drop_table('pbac_items')
    op.drop_index(op.f('ix_cycle_entries_user_id'), table_name='cycle_entries')
    op.drop_table('cycle_entries')
    op.drop_index(op.f('ix_form_submissions_user_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_template_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_hmb_statuses_user_id'), table_name='hmb_statuses')
    op.drop_table('hmb_statuses')
    op.drop_index(op.f('ix_form_templates_slug'), table_name='form_templates')
    op.drop_table('form_templates')
    # ### end Alembic commands ###
