"""update_clinical_note_to_submission_id

Revision ID: cdbfff70bf80
Revises: dbaf63b58b09
Create Date: 2026-07-10 09:23:55.351904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbfff70bf80'
down_revision: Union[str, Sequence[str], None] = 'dbaf63b58b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_notes', sa.Column('submission_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_clinical_notes_vitals_entry_id'), table_name='clinical_notes')
    op.create_index(op.f('ix_clinical_notes_submission_id'), 'clinical_notes', ['submission_id'], unique=False)
    op.drop_constraint(op.f('clinical_notes_vitals_entry_id_fkey'), 'clinical_notes', type_='foreignkey')
    op.create_foreign_key(None, 'clinical_notes', 'form_submissions', ['submission_id'], ['id'], ondelete='SET NULL')
    op.drop_column('clinical_notes', 'vitals_entry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_notes', sa.Column('vitals_entry_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clinical_notes', type_='foreignkey')
    op.create_foreign_key(op.f('clinical_notes_vitals_entry_id_fkey'), 'clinical_notes', 'pregnancy_vitals_entries', ['vitals_entry_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_clinical_notes_submission_id'), table_name='clinical_notes')
    op.create_index(op.f('ix_clinical_notes_vitals_entry_id'), 'clinical_notes', ['vitals_entry_id'], unique=False)
    op.drop_column('clinical_notes', 'submission_id')
    # ### end Alembic commands ###
