"""add_clinical_note_model

Revision ID: dbaf63b58b09
Revises: 14f1dfed3abf
Create Date: 2026-07-10 09:15:11.173786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaf63b58b09'
down_revision: Union[str, Sequence[str], None] = '14f1dfed3abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('clinician_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('vitals_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vitals_entry_id'], ['pregnancy_vitals_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_clinician_id'), 'clinical_notes', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_patient_user_id'), 'clinical_notes', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_vitals_entry_id'), 'clinical_notes', ['vitals_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_notes_vitals_entry_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_patient_user_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_clinician_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    # ### end Alembic commands ###
