"""add_report_and_room_to_labour

Revision ID: f03b98702968
Revises: b55e44f7152e
Create Date: 2026-07-08 12:48:36.136928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f03b98702968'
down_revision: Union[str, Sequence[str], None] = 'b55e44f7152e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('MONTHLY_FACILITY_SUMMARY', 'ANC_ATTENDANCE', 'REFERRAL_ACTIVITY', 'RISK_FLAG_SUMMARY', 'MOH_RMNCAH_SUBMISSION', name='report_type_enum'), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'CSV', 'EXCEL', name='report_format_enum'), nullable=False),
    sa.Column('status', sa.Enum('GENERATING', 'READY', 'FAILED', name='report_status_enum'), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_facility_id'), 'reports', ['facility_id'], unique=False)
    op.add_column('labour_sessions', sa.Column('room', sa.String(), nullable=True))
    op.drop_column('profiles', 'preferred_unit_ids')
    op.create_index(op.f('ix_scheduled_visits_baby_id'), 'scheduled_visits', ['baby_id'], unique=False)
    op.create_foreign_key(None, 'scheduled_visits', 'pregnancy_records', ['pregnancy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_visits', type_='foreignkey')
    op.drop_index(op.f('ix_scheduled_visits_baby_id'), table_name='scheduled_visits')
    op.add_column('profiles', sa.Column('preferred_unit_ids', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_column('labour_sessions', 'room')
    op.drop_index(op.f('ix_reports_facility_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
